events {}
http {
    include       mime.types;
    types {
        application/wasm                          wasm;
        application/octet-stream                  dll dat bin clr pdb;
        application/json                          json;
        application/javascript                    js mjs;
        text/css                                  css;
        text/html                                 html htm;
        image/png                                 png;
        image/svg+xml                             svg;
        image/x-icon                              ico;
    }
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
        }
    }
}
