version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: rapidq-api
    env_file:
      - ./api/.env
    ports:
      - "5187:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Issuer=RapidQApi
      - Jwt__Audience=RapidQClient
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: rapidq-client
    ports:
      - "5267:80"
    depends_on:
      - api

